// PART 1
#pragma config(Sensor, in1,    L_sensor,       sensorReflection)
#pragma config(Motor,  port4,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int searchLight(){
	int MaxLight = 1123; // max darkness
	int templight; // temporary value used for coping
	int MaxAngle;  // angle value of sensor where maximum brightness has been found
	int servo_pos = -127; // initial servo position

	motor[Servo] = -127; // set initial servo position - all the way clockwise
	wait1Msec(400);

	while(servo_pos<=127){ // 128 iterations in steps of 2
		//writeDebugStreamLine("%d\n", servo_pos);
		motor[Servo] = servo_pos; // set servo to the next position 
		wait1Msec(10); // give it time to move
		templight = SensorValue[L_sensor]; // store value of light

		if (templight<MaxLight){ // if brighter light found
			MaxLight = templight; // update max brightness found
			MaxAngle = servo_pos; // update angle of max brightness
		}
		servo_pos=servo_pos+2; // +2 rotation values in counter clockwise direction
	}

	motor[Servo] = MaxAngle; // point back to brightest direction
	wait1Msec(500); // wait for movement
	return MaxAngle; //return servo direction value at brightest direction
}

task main()
{
	wait1Msec(2000);
	while(true){ // loop forever
		writeDebugStreamLine("%d\n",searchLight()); // execute searchLight() and print 
		wait1Msec(1000); 					// servo direction value at brightest direction
	}

}
