#pragma config(Sensor, in1,    lightS,         sensorReflection) // light sensor = lightS
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop) //motors
#pragma config(Motor,  port3,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
* Light-Controlled Motor
* Continuously adjust speed of motor so that
* it is proportional to the light intesity received by the light sensor.
* Run fast in bright light, slow in dim light
*
*******************************************************************************/
task main() {

  	wait1Msec(2000); // give stuff time to turn on

  	// loop forever
  	while(true){
		//update integer lightamt to the light sensor's current SensorValue
		int lightamt = SensorValue[lightS];
    
    	//write the light amount value to debug stream with each iteration of the loop
    	writeDebugStreamLine("level: %d",lightamt); // value ranged from 0 to 1105

		//scale the light sensor value (1105-0) to motor value (0-127)
		//1105/9 ~= 123
    	lightamt = (1105 - lightamt)/9; 

		motor[leftMotor] = lightamt; // positive = forward
    	motor[rightMotor] = -lightamt; // negative = forward
  	}
}