#pragma config(Sensor, dgtl1,  sSONAR,         sensorSONAR_cm) //Sonar sensor sSONAR
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*******************************************************************************
* Anticipatory Obstacle Avoidance
* Uses a sonar sensor in order to back away from approaching obstacles.
*******************************************************************************/
task main() {
	
	int sonar; // holds the current value of the sonar in centimeters
	int dist = 20; // 20 centimeters. The robot will stop moving forward upon receiving a sonar 
  	
  	wait1Msec(2000); // give stuff time to turn on

  	// loop forever
  	while(true) {
    	sonar = SensorValue(sSONAR); //store current value of sonar sensor
    	writeDebugStreamLine("%d\n", sonar); //output value to debugger string

    	// If no object in sonar sensor range, move forward
	    if(sonar>dist) {

	    	motor[leftMotor] = 100; //go forwards
		    motor[rightMotor] = -100; //go forwards

		}
		//If the sonar senses an object, stop for 1 second and then back up for half of a second
		else{
		    motor[leftMotor]  = 0;  // stop motors
		    motor[rightMotor] = 0;  // stop motors
		    wait1Msec(1000);   		// for 1 second
		    motor[leftMotor] = -100; // go backwards
		    motor[rightMotor] = 100; // go backwards
		    wait1Msec(500);  		 // for half a second
		}
  	}
}
